version: "3.11"

services:
  backend:
    build: ./backend
    container_name: dashboard-backend
    env_file:
      - ./backend/.env
    ports:
      - "8001:8000"
    restart: always
    networks:
      - payment-net


networks:
  payment-net:
    external: true