from decimal import Decimal

from pydantic import BaseModel, Field

class AccountCreate(BaseModel):
    """
        Data required to create an new account
    """

    # Account name show on the dashboard
    name: str = Field(min_length=1, max_length=100, description="Customer's full name")


class AccountResponse(BaseModel):
    """
    Account information returned to the dashboard.
    """

    # Name of the customer.
    name: str

    # Card number automatically generated by the Payment API.
    # The API response should ideally contain a masked version
    # when this information is displayed to the dashboard.
    card_number: str

    # Current balance of the account.
    balance: Decimal


